<?php

declare(strict_types=1);

namespace Composer\Satis\VendorOverwrite;


use Composer\Config;
use Composer\EventDispatcher\EventDispatcher;
use Composer\IO\IOInterface;
use Composer\Util\RemoteFilesystem;

class RepositoryFactory extends \Composer\Repository\RepositoryFactory
{
    /**
     * @param IOInterface $io
     * @param Config $config
     * @param EventDispatcher|null $eventDispatcher
     * @param RemoteFilesystem|null $rfs
     * @return \Composer\Repository\RepositoryManager|void
     */
    public static function manager(
        IOInterface $io,
        Config $config,
        EventDispatcher $eventDispatcher = null,
        RemoteFilesystem $rfs = null
    ) {
        $manager =  parent::manager($io, $config, $eventDispatcher, $rfs); // TODO: Change the autogenerated stub
        $manager->setRepositoryClass('git+monorepo', VcsRepository::class);
        return $manager;
    }

}